openapi: 3.0.3
info:
  title: ARX TRACK API
  description: |
    API for the ARX TRACK ecosystem — an advanced platform for wallet tracking, real-time AI-driven trading signals, automation, and analytics for Web3 traders.
  contact:
    name: ARX TRACK Team
    email: support@arxtrack.fun
  version: 1.0.0
servers:
  - url: https://virtserver.swaggerhub.com/arx-a65/arx/1.0.0
    description: SwaggerHub API Auto Mocking
  - url: https://api.arxtrack.fun/v1
    description: Production API
  - url: https://staging-api.arxtrack.fun/v1
    description: Staging API
tags:
  - name: Wallets
    description: Operations for retrieving wallet profiles and on-chain data.
  - name: Signals
    description: Real-time AI-generated trading signals based on wallet activity.
  - name: Automation
    description: Manage automated trading rules based on detected signals or conditions.
  - name: AI
    description: AI engine queries for analytics and trading recommendations.
  - name: Market Data
    description: Access aggregated token, liquidity pool, and price feed data.
  - name: Portfolio
    description: Track portfolio performance, allocation, and PnL over time.
paths:
  /wallets/{address}:
    get:
      tags:
        - Wallets
      summary: Get wallet profile
      description: |
        Retrieve public wallet information, AI reputation score, balance details, and on-chain activity.
      parameters:
        - name: address
          in: path
          description: Public wallet address (Solana, Ethereum, etc.)
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Wallet profile retrieved successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/inline_response_200"
              example:
                address: 4kD3bF2xE9j8YsEPrLfZ1a7C2wz...
                chain: Solana
                reputationScore: 87
                riskLevel: LOW
                totalValueUSD: 152300.55
                tokens:
                  - symbol: SOL
                    balance: 530
                  - symbol: USDC
                    balance: 24500
                  - symbol: ARX
                    balance: 1200
        "404":
          description: Wallet not found
  /signals/latest:
    get:
      tags:
        - Signals
      summary: Get latest trading signals
      description: Returns the most recent AI-generated trading signals.
      parameters:
        - name: limit
          in: query
          description: Maximum number of signals to return
          required: false
          schema:
            maximum: 100
            minimum: 1
            type: integer
            default: 10
      responses:
        "200":
          description: List of trading signals
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/inline_response_200_1"
              example:
                - id: sig_001
                  type: BUY
                  token: ARX
                  confidence: 0.92
                  timestamp: 2025-08-08T07:16:41Z
                - id: sig_002
                  type: SELL
                  token: SOL
                  confidence: 0.85
                  timestamp: 2025-08-08T07:20:13Z
                - id: sig_003
                  type: WATCH
                  token: ETH
                  confidence: 0.76
                  timestamp: 2025-08-08T07:25:02Z
  /automation/rules:
    post:
      tags:
        - Automation
      summary: Create automated trading rule
      description: Configure a rule to execute automated orders based on detected activity or AI signals.
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/automation_rules_body"
            example:
              wallet: 4kD3bF2xE9j8YsEPrLfZ1a7C2wz...
              action: BUY
              token: ARX
              amount: 50
              slippage: 1
              condition: price_above_100
        required: true
      responses:
        "201":
          description: Rule created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/inline_response_201"
              example:
                ruleId: auto_001
                status: ACTIVE
  /automation/rules/{ruleId}:
    delete:
      tags:
        - Automation
      summary: Delete automated trading rule
      description: Deletes an automated trading rule by its unique ID.
      parameters:
        - name: ruleId
          in: path
          description: Rule ID to delete
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Deletion confirmation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/inline_response_200_2"
              example:
                deleted: true
        "404":
          description: Rule not found
  /ai/analyze:
    post:
      tags:
        - AI
      summary: Run AI analysis
      description: Send wallet or token data for AI-powered analysis and recommendations.
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ai_analyze_body"
            example:
              type: wallet
              target: 4kD3bF2xE9j8YsEPrLfZ1a7C2wz...
        required: true
      responses:
        "200":
          description: AI analysis results
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/inline_response_200_3"
              example:
                summary: Wallet is accumulating ARX and distributing USDC.
                recommendations:
                  - Consider holding ARX short-term.
                  - Monitor USDC liquidity pools.
                  - Set an alert if ARX price drops 5%.
components:
  schemas:
    inline_response_200:
      type: object
      properties:
        address:
          type: string
          description: Wallet address
        chain:
          type: string
          description: Blockchain network (Solana, Ethereum, Binance Smart Chain, Polygon, etc.)
        reputationScore:
          type: integer
          description: AI-calculated reputation score (0-100)
        riskLevel:
          type: string
          description: Calculated risk level
          enum:
            - LOW
            - MEDIUM
            - HIGH
            - CRITICAL
        totalValueUSD:
          type: number
          description: Estimated total value in USD
          format: float
        tokens:
          type: array
          description: List of tokens with balances
          items:
            type: object
            properties:
              symbol:
                type: string
              balance:
                type: number
    inline_response_200_1:
      type: object
      properties:
        id:
          type: string
        type:
          type: string
          description: Type of signal (buy, sell, watch, hold)
          enum:
            - BUY
            - SELL
            - WATCH
            - HOLD
        token:
          type: string
        confidence:
          type: number
          description: AI confidence score (0-1)
          format: float
        timestamp:
          type: string
          format: date-time
    automation_rules_body:
      required:
        - action
        - amount
        - slippage
        - token
        - wallet
      type: object
      properties:
        wallet:
          type: string
          description: Wallet to monitor
        action:
          type: string
          description: Action to trigger when rule conditions are met
          enum:
            - BUY
            - SELL
            - WATCH
            - HOLD
        token:
          type: string
          description: Token to buy, sell, or monitor
        amount:
          type: number
          description: Amount of tokens to execute in trade
        slippage:
          type: number
          description: Maximum acceptable slippage percentage
        condition:
          type: string
          description: Optional condition for triggering rule (e.g., "price_above_100", "volume_spike")
    inline_response_201:
      type: object
      properties:
        ruleId:
          type: string
        status:
          type: string
    inline_response_200_2:
      type: object
      properties:
        deleted:
          type: boolean
    ai_analyze_body:
      required:
        - target
        - type
      type: object
      properties:
        type:
          type: string
          description: Type of target to analyze
          enum:
            - wallet
            - token
            - liquidity_pool
        target:
          type: string
          description: Wallet address, token symbol, or liquidity pool ID
    inline_response_200_3:
      type: object
      properties:
        summary:
          type: string
        recommendations:
          type: array
          items:
            type: string
